Kaholo/PM-server

- client/src/app/shared/popups/servers-popup/servers-popup.component.html
> PMG-42 Add Server Panel: Remove the word "Only"

- client/src/app/shared/popups/servers-popup/servers-popup.component.css
- client/src/app/shared/popups/servers-popup/servers-popup.component.html
Added pull right class.
For some reason it override the padding so i added margin to the class.
> PMG-41 Add Server Panel: Buttons should be on the right

- client/src/assets/css/style.css
Ignoring the node wrapper active class.
> PMG-32 Map Tree: inconsistent hover colors

- client/src/app/admin-panel/dedicated-agents/dedicated-agents.component.css
> PMG-21 Plugin Panel: Eye icon not same as Trash icon

- client/src/assets/css/style.css
Changed map logo in tree project
> PMG-79 Map Tree - Map displayed as folder

- client/src/app/admin-panel/admin-panel.component.html
- client/src/app/admin-panel/dedicated-agents/dedicated-agents.component.html
- client/src/app/admin-panel/servers/servers.component.html
- client/src/app/app.routing.ts
- client/src/app/map-managment/map-settings/map-servers/map-servers.component.html
- client/src/app/map-managment/map-settings/map-settings.component.html
- client/src/app/shared/popups/servers-popup/servers-popup.component.html
Changed treminology: server to agent and dedicated agents to plugins.
> PMG-87 Terminology Change : Server -> Agent

- client/src/app/map-managment/map-managment.component.ts
Solved prod conflict - changed open maps to public
> PMG-63 UI - Refreshing the browser should return to the same map

- client/src/app/map-managment/left-panel/left-panel.component.css
- client/src/app/map-managment/left-panel/left-panel.component.html
- client/src/app/map-managment/left-panel/left-panel.component.ts
- client/src/app/map-managment/left-panel/map-explorer/map-explorer.component.css
Added sidebar to project tree; aligned add project btn.
> PMG-77 Projects tree overflow to message container.

- client/src/app/map-managment/left-panel/map-explorer/map-explorer.component.ts
> PMG-108 Maps do not open

- client/src/app/map-managment/left-panel/left-panel.component.html
- client/src/app/map-managment/left-panel/left-panel.component.ts
- client/src/app/map-managment/map-managment.component.html
- client/src/app/map-managment/map-managment.component.ts
> PMG-77 Projects tree overflow to message container

- client/src/app/shared/popups/servers-popup/servers-popup.component.html
> PMG-106 Plugins not installed to the agents

- client/src/app/map-managment/map-managment.component.ts
- client/src/app/shared/services/map.service.ts
> PMG-118 Open maps tabs doesn't show

- client/src/assets/css/style.css
> PMG-121 In select agents popup, selecting a folder should select all descendants

- client/src/app/admin-panel/triggers/add-trigger/add-trigger.component.css
> PMG-19 Add Trigger drop downs looks fat

- client/src/app/admin-panel/servers/new-group/new-group.component.html
- client/src/app/admin-panel/servers/new-group/new-group.component.ts
- client/src/app/admin-panel/servers/servers.component.html
- client/src/app/admin-panel/servers/servers.component.ts
> PMG-110 Agents Managment - Rename group not working

- client/src/app/shared/services/authentication.service.ts
Added auth option to request headers
> PMG-128 Components guard stop working

- client/src/app/map-managment/map-settings/map-attributes/map-attributes.component.ts
- client/src/app/shared/popups/attribute-window/attribute-window.component.ts
> PMG-76 Admin Server Attribute crash!!! when adding list attribute

- client/src/app/map-managment/map-editor/map-code-editor/map-code-editor.component.ts
- client/src/app/map-managment/map-editor/map-editor.component.ts
Once changing map, return to map design view.
> PMG-132 Map code doesnt update new map

- client/src/app/admin-panel/servers/servers.component.html
Fix bug (added check for agent key)
> PMG-145 Agent folder tree double the content

- client/package.json
added ngx-toastr to package.json
> PMG-142 add toastr notification

- client/src/app/shared/popups/servers-popup/servers-popup.component.html
- client/src/app/shared/popups/servers-popup/servers-popup.component.ts
> PMG-146 Arrange the plugin repos and directories

- server/api/controllers/PluginController.js
- server/api/services/PluginService.js
Change config process to chunk
> PMG-151 Can't install plugin with long config file

- client/src/app/map-managment/map-editor/map-code-editor/map-code-editor.component.css
Changed code editor background
> PMG-155 map code view doesn't resizes on messages resize

- console/src/app/plugins/plugins-list/plugins-list.component.html
- console/src/app/plugins/plugins-list/plugins-list.component.scss
> PMG-164 Plugins icons are missing

- console/src/environments/environment.prod.ts
hardcoded server url for testing
> PMG-176 Fix production server url

- server/app.js
> PMG-177 Can't refresh the page

- .gitignore
- server/libs/sdk.js
Removed libs from gitignore, added gitkeep
> PMG-173 Add plugin icons to map design

- server/api/controllers/maps.controller.js
- server/api/services/projects.service.js
Changed project map push method (mongoose method isn't compatible with mongo 3.6+)
> PMG-179 After adding a Map to project - the list still remains empty

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/plugin-toolbox/plugin-toolbox.component.ts
> PMG-165 Plugin on left pane should have a cubic look

- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-attributes/add-attribute/add-attribute.component.html
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-attributes/add-attribute/add-attribute.component.ts
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-attributes/map-attributes.component.html
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-attributes/map-attributes.component.ts
Enabled attribute editing. Added validator for attribute name
> PMG-171 Edit map attribute

- console/src/app/projects/projects-list/projects-list.component.scss
- console/src/styles.scss
> PMG-208 align card title and text in cards tile

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.scss
- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/plugin-toolbox/plugin-toolbox.component.ts
- console/src/styles.scss
Removed link breakpoints and updated node style
>  PMG-215 Change map design to new design

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.html
- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
- console/src/app/maps/map-detail/map-edit/map-edit.component.html
> PMG-227 UI - on process panel on the right

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.scss
> PMG-220 UI - Magnifires

- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-agents/select-agent/select-agent.component.html
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-attributes/add-attribute/add-attribute.component.html
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-triggers/trigger-form/trigger-form.component.html
- console/src/styles.scss
> PMG-229 UI - update modal design

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
Node is highlighted when selected
> PMG-218 UI - fix nodes

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
Not allowing links without target
> PMG-187 A link can be created without connection to destination node

- console/src/app/calendar/calendar-container/calendar-container.component.html
- console/src/app/calendar/calendar-container/calendar-container.component.scss
- console/src/app/calendar/calendar/calendar.component.html
- console/src/app/calendar/calendar/calendar.component.scss
- console/src/styles.scss
> PMG-236 UI - calendar

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
Change stroke width and selected node color
> PMG-244 Fix dropped node ui

- console/src/app/app.component.html
- console/src/app/app.module.ts
- console/src/app/maps/map-detail/map-edit/map-edit.component.html
> PMG-233 add tooltips to navs

- console/src/app/plugins/plugin-upload/plugin-upload.component.html
- console/src/app/plugins/plugins-list/plugins-list.component.html
> PMG-249 Can't add new plugins (add plugin is missing)

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.html
- console/src/app/maps/map-detail/map-edit/map-edit.component.ts
- console/src/app/maps/maps-list/maps-list.component.html
- console/src/app/projects/project-details/project-details.component.html
- console/src/app/projects/project-details/project-details.component.scss
- console/src/app/projects/projects-list/projects-list.component.html
> PMG-258 resolve build prod issues

- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-attributes/map-attributes.component.html
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-attributes/map-attributes.component.ts
- console/src/app/maps/models/map-structure.model.ts
Fix add attribute production bugs
> PMG-262 add attribute in production crashes

- server/api/services/map-execution.service.js
> PMG-261 serial flow skips first node

- server/api/controllers/plugins.controller.js
Fix installation bug in emitting
> PMG-264 fix plugin installation

- server/api/services/map-execution.service.js
fix result creating condition bug
> PMG-266 execution result not creating after executing map

- console/src/app/maps/map-detail/map-edit/map-edit.component.html
- console/src/app/maps/map-detail/map-edit/map-edit.component.scss
Adjusted close enviroment tab arrow position
> PMG-253 Enviorment panel - Not by design

- console/src/app/maps/map-detail/map-detail.component.ts
> PMG-257 Leaving map without saving - typo

- console/src/app/core/app.component.html
- console/src/app/core/app.component.scss
- console/src/assets/sass/_variables.scss
updated background and active properties
> PMG-268 add active and hover background to nav

- console/src/app/projects/project-details/project-details.component.html
- console/src/app/projects/project-details/project-details.component.scss
Added 'add map' button at bottom of project detail page
> PMG-190 Project page - Missing "Add Map" Button

- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.html
Added placeholders to action time parameters
> PMG-263 Missing filter agents field

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.html
- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.ts
Fixed bug (showing action method select )
> PMG-267 Cant see plugins methods on edit process (map already created)

- console/src/app/plugins/plugins-list/plugins-list.component.scss
Added margin and decrease plugin image size
> PMG-255 Plugins view - join icon and name

- console/src/styles.scss
> PMG-272 UI - general

- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.html
remove duplicate process option
> PMG-256 Map design - remove duplicate button

- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.ts
using new instead remove at when selecting method while editing action
> PMG-280 Method params are not changing when changing to another method

- server/api/services/maps.service.js
- server/api/services/projects.service.js
> PMG-279 Add archive map button

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.ts
> PMG-300 Save action doesn't work

- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.html
- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.scss
> PMG-284 Process save button override the text

- server/api/services/map-execution.service.js
Changed process status definition
> PMG-301 mix execution result

- console/src/app/maps/map-detail/map-detail.component.ts
> PMG-295 version number in show history is not consistent

- console/src/app/maps/map-detail/map-result/map-result.component.ts
- server/api/services/map-execution.service.js
> PMG-304 Executions Result - action raw output not displayed

- console/src/app/maps/map-detail/map-revisions/map-revisions.component.ts
> PMG-305 Map Revisions - Allow dragging map

- console/src/app/maps/map-detail/map-result/map-result.component.html
- console/src/app/maps/map-detail/map-result/map-result.component.ts
- server/api/services/map-execution.service.js
Update template and component to prevent errors for empty results
> PMG-312 Map results throws error when map result is empty

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
Update map structure when moving processes
> PMG-314 Map save should save map design

- console/src/app/maps/map-detail/map-edit/map-edit.component.ts
Correcting incorrect property deletion
> PMG-319 Import & Export map

- console/src/app/maps/map-detail/map-detail.component.ts
> PMG-319 Import  & Export map

- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.html
- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.ts
> PMG-334 Cannot rename action

- console/src/app/maps/map-detail/map-result/map-result.component.ts
- console/src/app/maps/maps.service.ts
checking execution on map result init
> PMG-336 Execution result - raw output message on action start

- server/api/controllers/maps.controller.js
> PMG-320 Can't delete a Trigger

- server/api/controllers/maps.controller.js
- server/api/services/map-execution.service.js
Stopping map when mandatory process fails
> PMG-350 Execution Process - Mandatory process

- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.html
Hide correlate agents and filter agents in process form
> PMG-348 Execution Process - Hide filter agents option

- server/api/services/map-execution.service.js
Not calling next node when condition failed
> PMG-349 Execution Process - Agent flow

- console/src/app/agents/groups/groups.component.ts
> PMG-354 Agents Groups

- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-agents/map-agents.component.ts
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-agents/select-agent/select-agent.component.ts
- server/api/services/map-execution.service.js
bug fix - error stopping map when first process has a condition that failed
bug fix - process name wasn't saved to execution results
@time 1h
> PMG-361 Problem with calculation of map flow with two parallel processes

- console/src/app/maps/map-detail/map-edit/map-design.service.ts
- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.html
- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.ts
fix bug - added subject to update process changes
> PMG-346 Deleting a link doesn't effect the process flow selection

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
Adjust the deviation when dropping plugin
> PMG-360 Plugins drop at the wrong location

- server/api/services/maps.service.js
> PMG-357 Updated map column doesn't work

- console/package.json
- console/src/app/maps/map-detail/map-result/map-result.component.ts
- server/api/controllers/maps.controller.js
- server/env/config.json
> PMG-367 stop button only show if executing map on execution results view

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.ts
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/plugin-toolbox/plugin-toolbox.component.ts
Fix bug - typo in find function when adding a link
> PMG-368 can't open process for edit after deleting link

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
> PMG-372 hooks doesn't save when saving process

- console/src/app/maps/map-detail/map-detail.component.ts
> PMG-374 save map when trying to navigate away from map view doesn't work

- console/src/app/agents/groups/evaluate-group-agent/evaluate-group-agent.component.ts
fix false filter number if no filters
> PMG-375 deleting an agent doesn't delete it from group

- console/src/app/maps/map-detail/map-result/map-result.component.html
- console/src/app/maps/map-detail/map-result/map-result.component.scss
- console/src/app/maps/map-detail/map-result/map-result.component.ts
- console/src/styles.scss
Fix agent select bug and UI fix
> PMG-380 aggregation error in result screen

- console/src/app/maps/map-detail/map-revisions/map-revisions.component.ts
fixbug - Added start point to revisions
> PMG-382 Revisions - Preview doesn't work if not going through design

- console/src/app/agents/agents-list/agents-list.component.html
> PMG-383 Admin Agents - Add icons tooltips

- server/api/services/map-execution.service.js
Fix error in setting process status
> PMG-384 Process aggregation status error

- server/api/controllers/maps.controller.js
Checking configuration in execution api
> PMG-386 Add configuration to map executer plugin

- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
fix closing process form pane on delete
> PMG-388 deleting process should close process edit pane

- console/src/app/calendar/calendar/calendar.component.html
- console/src/app/calendar/calendar/calendar.component.scss
> PMG-369 Can't delete a scheduled map

- server/api/services/agents.service.js
stop updating agent document when registering
> PMG-389 agent restart overwrite current data

- console/src/app/core/app.component.html
Added link to productionmap.com
> PMG-387 add link to documentation in navbar

- server/api/controllers/agents.controller.js
- server/api/services/map-execution.service.js
update agent filtering in map execution
> PMG-391 server sending agents key to client

- console/package.json
- console/src/app/maps/map-detail/map-result/process-result/process-result.component.ts
Install moment js; Fix action finish time error
> PMG-397 Execution Result - Displayed finish time is wrong

- server/api/services/map-execution.service.js
Updating result object after process finish
> PMG-393 Map Execution results - process and actions not displayed

- console/src/app/maps/interfaces/map.interface.ts
- console/src/app/maps/map-detail/map-detail.component.ts
- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.ts
- console/src/app/maps/models/map.model.ts
- server/api/models/map-structure.model.js
> PMG-302 Save Changes popup when no change really happened

- server/api/services/map-execution.service.js
> PMG-396 Execution Result - add "triggered by" and configuration

- console/src/app/maps/map-detail/map-result/map-result.component.html
- console/src/app/maps/map-detail/map-result/map-result.component.ts
- console/src/app/maps/map-detail/map-result/process-list-item/process-list-item.component.html
- console/src/app/maps/map-detail/map-result/process-list-item/process-list-item.component.scss
- console/src/app/maps/map-detail/map-result/process-list-item/process-list-item.component.ts
- console/src/app/maps/maps.module.ts
- console/src/app/maps/models/index.ts
- console/src/app/maps/models/process-result.model.ts
Created process-list-item component and added it to map-result
> PMG-401 add status icon to process list in map result

- console/src/app/maps/map-detail/map-result/process-result/process-result.component.html
Fixed result display in action table
> PMG-400 action result isn't displayed in action table

- server/api/services/map-execution.service.js
> PMG-405 empty action cause error in execution and stop

- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/map-triggers/trigger-form/trigger-form.component.ts
- server/api/models/plugin.model.js
Remove required validator from configuration in trigger form
Signed-off-by: Roy Talyosef <roy@productionmap.com>
> PMG-408 Trigger - Configuration should not be mandatory

- server/api/services/map-execution.service.js
fix merge error in summarizing execution
> PMG-403 Map finish with process with status 'executing'

- console/src/app/projects/projects-list/projects-list.component.html
- console/src/app/projects/projects-list/projects-list.component.scss
Added "Add project" button in projects list
Signed-off-by: Roy Talyosef <roy@productionmap.com>
> PMG-281 On Project Panel - need to add add project button at the bottom

- server/env/config.json
> PMG-413 DbURI is hard coded

- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.html
- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.ts
- server/api/models/map-structure.model.js
- server/api/services/map-execution.service.js
not saving timeout as a default value.
if no value, default timeout is set to 10 min
> PMG-414 Timeout and Retries to action executions

- console/src/app/maps/map-detail/map-revisions/map-revisions.component.html
- console/src/app/maps/map-detail/map-revisions/map-revisions.component.scss
- console/src/app/maps/map-detail/map-revisions/map-revisions.component.ts
- console/src/app/maps/map-detail/map-revisions/process-view/process-view.component.html
- console/src/app/maps/map-detail/map-revisions/process-view/process-view.component.ts
- console/src/app/maps/maps.module.ts
Added process view to map revisions
> PMG-419 add process select to map revisions

- console/src/app/maps/map-detail/map-revisions/map-revisions.component.html
- console/src/app/maps/map-detail/map-revisions/map-revisions.component.scss
- console/src/app/maps/map-detail/map-revisions/map-revisions.component.ts
Add code view to map-revisions component
> PMG-418 add design/code tabs to map revisions

- server/api/services/map-execution.service.js
- server/libs/sdk.js
Update context, add iteration to sdk functions
> PMG-427 fix sdk errors

- console/src/app/maps/map-detail/map-edit/map-design/process-form/process-form.component.ts
Add options inputs to method context
> PMG-428 add input types to process-form

- .gitignore
- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/plugin-toolbox/plugin-toolbox.component.ts
- console/src/app/plugins/models/plugin.model.ts
- console/src/app/plugins/plugins-list/plugins-list.component.html
- console/src/app/plugins/plugins-list/plugins-list.component.ts
- console/src/app/plugins/plugins.service.ts
Showing the image in the plugin-toolbox component.
with the fullimgurl() in map design, plugin-list and plugin-toolbox instead to pass an fixed url.
> PMG-434 Plugins icons not appear on local enviorments

- console/src/app/maps/map-detail/map-result/map-result.component.html
- console/src/app/maps/map-detail/map-result/map-result.component.scss
- console/src/app/maps/map-detail/map-result/map-result.component.ts
* changed to use view
* hide overflow on parent
* display grid
> PMG-435 map-result: pie charts overflows parent

- console/src/app/maps/maps-list/maps-list.component.html
- console/src/app/maps/maps-list/maps-list.component.ts
*on delete map in map list adding a loop to search which index of featuredMap is relevant to the map
> PMG-444   Maps List - Map remains in feature

- console/src/app/maps/map-create/map-create.component.ts
- console/src/app/maps/models/map.model.ts
- server/api/models/map.model.js
*by default description is string empty
> PMG-451   Map properties - Description field causes unsaved changes

- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/plugin-toolbox/plugin-toolbox.component.ts
* remove Object.assign to the plguins to keep TS class
> PMG-445 Plugins Toolbox - Default image is displayed instead of plugin icon

- server/api/controllers/setup.controller.js
adding connect observable to mongoose instead to check if dburi exist
> PMG-460   dbUri

- server/api/services/map-execution.service.js
* add require and console to all contexts
> PMG-459 Map Code - Support require for common packages

- console/src/app/maps/map-detail/map-detail.component.ts
- console/src/app/maps/map-detail/map-edit/map-design/map-design.component.ts
*updating the structure when we change targetId of the arrow
> KG-462   Moving Link keeps old process

- server/api/services/plugins.service.js
- server/api/validation-schema/plugin-config.schema.js
*to avoid case that options object not same to {id,name}
> KG-466   Action Params - Dropdown value not saved

- console/src/app/core/dashboard/dashboard.component.scss
- console/src/app/maps/maps-list/maps-list.component.scss
- console/src/app/plugins/plugins-list/plugins-list.component.scss
- console/src/app/projects/project-details/project-details.component.scss
- console/src/app/projects/projects-list/projects-list.component.scss
- console/src/assets/sass/_mixins.scss
> KG-470   Tables - Design

- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/plugin-toolbox/plugin-toolbox.component.scss
- console/src/app/maps/map-detail/map-edit/map-enviroment-pane/plugin-toolbox/plugin-toolbox.component.ts
* set height to svg
* add overflow to graph
> KG-475 Plugins toolbox - should be able to scroll

- console/src/app/app.module.ts
- console/src/app/core/app.component.ts
- console/src/app/core/setup/issetup.guard.ts
- console/src/app/core/setup/settings.service.ts
- console/src/app/core/setup/setup.component.ts
> Release 1.2.4 fix

- server/api/services/maps.service.js
> KG-632 Paging not updated

- .gitignore
- server/api/tests/helpers/global-setup.js
- server/api/tests/helpers/global-teardown.js
- server/api/tests/map-execution.test.js
- server/api/tests/map-revisions.test.js
- server/api/tests/plugins.test.js
- server/env/config.test.json
- server/env/enviroment.js
This fixes a lack of consistency during our tests.
> Disable Mongo in Memory Database temporarily

- server/api/services/map-execution.service.js
* setting map structure into a variable instead of memory general variable (caused wrong steps)
> KAH-110 Stealing step from another map

- server/api/controllers/agents.controller.js
- server/api/models/agent.model.js
- server/api/models/group.model.js
- server/api/services/agents.service.js
- server/api/services/map-execution.helper.js
- server/api/services/map-execution.service.js
- server/helpers/bootstrap.js
added agentStatusSchema to agentSchema in agent.model
all of the data is persisted in model, except intervalId
as commented in the agents.service:
> // TODO: refactor into scheduler microservice
// why?
// - in node.js, setInterval returns a reference to Timout class instance, not intervalId handle number
//   that's why it's impossible to save a reference to it in a model
> Feature/KAH-97 (Adjust agents service for stateless app)

- console/src/app/maps/map-detail/map-revisions/map-revisions.component.html
removed unused parameter to th  onResize function
> Errors when building app

- console/src/app/maps/map-detail/map-properties/map-properties.component.ts
* fix project assigning
* move projects retrival from the getCurrentMap to prevent infinite loop
> KAH-40 Cannot change project to a specific map

- server/api/services/map-execution.service.js
* check if any of the actions of the process failed, if so finish execution
> KAH-175 Mandatory process not work

- server/libs/sdk.js
* issues using let/const inside vm.runInNewContext
There is some kind of issue when doing `vm.runInNewContext` using let and consts instead of var, that don't allow the execution context object to override the variables
> KAH-188 All executions context are undefined

- server/api/services/map-execution.helper.js
- server/helpers/create-key.js
* fix agents status check
* remove duplicate generateKey function
> KAH-303 Vault - encryption key changes on restart
